### PR TITLE
Add more Homebrew to the page for the future.

### PR DESCRIPTION
**Pull request by henryiii**
Much simpler and works for lots of things. See my setup page: https://iscinumpy.gitlab.io/post/setup-a-new-mac/

### CODE REVIEW

**Comment by kratsg** [comment]
Linuxbrew also exists -- so can almost unequivocally recommend "brew" formulas for both.

**Comment by smeehan12** [comment]
It says that this PR is a "draft" - are you still working on it then? Or is it just saying this because all checks failed?

**Comment by henryiii** [comment]
It was due to adding one more commit, and now is because of failures.

I’m not sure linuxbrew is as unequivocally recommendable; macOS is more uniform and doesn’t already have a package manager. I don’t know what the level of support for LinuxBrew is. Someone familiar with it can verify (it’s been ~3 years since I played with it, and I know you are no longer allowed to put linuxbrew modifications in the core formula repo).

**Comment by henryiii** [comment]
Ah, they are different repos now, and it looks they have binaries and are up to date. Nice!

**Comment by henryiii** [comment]
I think that's ready to go now.

**Pull request merged**
